### PR TITLE
Fixes for unexpected flags not crashing out properly. Fixes #47

### LINKED ISSUE #47: How do you use the ShowHelpOnUnexpected option for DefaultParser?
I tried using the option as shown here:

https://github.com/integrii/flaggy/blob/master/README.md#recommended-program-structure

and with tag `1.2.2` (425304205580254c6ea87908f35848c46eb99d5e) I *do* see the help output when I use an invalid flag, but *only* if I don't specify a value for the flag when I specify the flag.

Example program:

```golang
package main

import (
	"fmt"

	"github.com/integrii/flaggy"
)

func main() {

	optBool := false
	optIntegerTestVar := 1
	optStringTestVar := "My test string"

	flaggy.SetName("Test")
	flaggy.SetDescription("Short example to illustrate issue")

	flaggy.DefaultParser.ShowHelpOnUnexpected = true

	// Add flags
	flaggy.Bool(&optBool, "bo", "bool", "Boolean test option")
	flaggy.Int(&optIntegerTestVar, "int", "inttest", "Integer test option")
	flaggy.String(&optStringTestVar, "str", "stringtest", "String test option")

	// Parse the flag
	flaggy.Parse()

	fmt.Printf("%v\n", optBool)
	fmt.Printf("%v\n", optIntegerTestVar)
	fmt.Printf("%v\n", optStringTestVar)

}
```

Example usage:

```ShellSession
$ go run main.go -warning
Test - Short example to illustrate issue

  Flags:
       --version  Displays the program version string.
    -h --help  Displays help with available flag, subcommand, and positional value parameters.
    -bo --bool  Boolean test option
    -int --inttest  Integer test option (default: 1)
    -str --stringtest  String test option (default: My test string)

Expected a following arg for flag warning, but it did not exist.
exit status 2
```

```ShellSession
$ go run main.go -warning=no
false
1
My test string
```

```ShellSession
$ go run main.go --warning=no
false
1
My test string
```

### PR DESCRIPTION
**Pull request by integrii**

### CODE REVIEW

File: flaggy_test.go [hunk 1]
```diff
@@ -106,7 +106,7 @@ func TestComplexNesting(t *testing.T) {
 }
 
 func TestParsePositionalsA(t *testing.T) {
-	inputLine := []string{"-t", "-i=3", "subcommand", "-n", "testN", "-j=testJ", "positionalA", "positionalB", "--testK=testK", "--", "trailingA", "trailingB"}
```
Comment (ravenpride) [inline flaggy_test.go]: `-i=3` should be covered by a global flag and `--testK=testK` is a valid subcommand flag.
What was wrong with this line?

**Comment by ravenpride** [comment]
My application does not make use of subcommands, so I've tested it with an unkown global flag at the global level and it does not work.  No error is reported.

**Comment by integrii** [comment]
I agree - this is totally broken still.  Taking a look.  I pulled those flags out because I went too quickly and didn't notice that those were in fact valid flags in that test.

**Comment by integrii** [comment]
Still working on new code to solve #47.  This involves a new code path as described below:

- Each subcommand (and the parser) keep track of all key/value pairs used in a new property (`parsedArgs`)
- Each subcommand (and the parser) all have a new method that returns all key/value pairs parsed on the parser struct the call was invoked on and all child subcommands within it.
- A new `func` is created and called when the root parser parses arguments.  This func finds all the parsed args recursively, then reads the incoming arg values from the user to detect if any values were ignored or not found in any tracked subcommand's `parsedArgs` properties
- if unknown values are found on the input arguments, an error is raised and the program exits, but only if ShowHelpOnUnexpected is used.

**Comment by integrii** [comment]
Okay, all tests pass!  Take a look.  There is a lot of code here so if you don't get through all of it, no big deal.  I am going to add some more tests before merging, I think - just to be sure.

**Comment by ravenpride** [comment]
This is a really significant modification. Thank you very much!
I've played around with it and unknown flags at the global level are detected properly now, but I'm sorry to say that unkown flags behind a subcommand are not recognized appropriately.

**Comment by ravenpride** [comment]
I'm sorry to say that, but the unit tests on branch #47 are failing on my side.

**Comment by integrii** [comment]
D'oh!  I'll take a look again and see if I missed something.

File: subCommand.go [hunk 2]
```diff
@@ -212,6 +216,13 @@ func (sc *Subcommand) parse(p *Parser, args []string, depth int) error {
 
 	// if a command is parsed, its used
 	sc.Used = true
+	debugPrint("used subcommand", sc.Name, sc.ShortName)
```
Comment (integrii) [inline subCommand.go]: i could probably make this smarter so that we don't add positionals for the short or long name that wasn't used.  Right now, we add a positional for both the short and long names anytime the subcommand is invoked.

**Comment by integrii** [comment]
Okay, check it out now.  I don't know what I was thinking before when I said tests pass.  I must have somehow fooled myself.

I promise, tests pass now:

image

**Comment by ravenpride** [comment]
@integrii
I can confirm that the tests pass now and that my own test input works as expected.
Thank you very much for this awesome piece of work!
